services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: uas-english
        working_dir: /var/www
        volumes:
            - .:/var/www
        ports:
            - 9000:9000
        extra_hosts:
            -   "host.docker.internal:host-gateway"

    webserver:
        image: nginx:alpine
        container_name: nginx_server
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"
        depends_on:
            - app


networks:
    appnet:
        driver: bridge
