version: '3.8'

services:
    app:
        image: laravelphp/php-fpm
        container_name: laravel_app
        working_dir: /var/www
        volumes:
            - .:/var/www
        ports:
            - 9000:9000
        depends_on:
            - mysql

    webserver:
        image: nginx:alpine
        container_name: nginx_server
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
        depends_on:
            - app

    mysql:
        image: mysql:8.0
        container_name: mysql_db
        restart: always
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - "3306:3306"

volumes:
    mysql_data:
